<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "camaliga"
 *
 * Auto generated by Extension Builder 2013-09-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Camaliga: Carousel/Map/List/Gallery',
	'description' => 'A powerful and modern extbase carousel/gallery/map/list extension that can use the TYPO3 categories. You can use different jQuery-plugins.',
	'category' => 'plugin',
	'author' => 'Kurt Gusbeth',
	'author_email' => 'info@quizpalme.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>